# Generated by Django 3.2.13 on 2024-07-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localproj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
