# Generated by Django 5.0.7 on 2024-07-15 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localproj', '0002_project_status'),
        ('mentor', '0005_alter_mentors_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='posted_by',
            field=models.ForeignKey(default=37, on_delete=django.db.models.deletion.CASCADE, to='mentor.mentors'),
        ),
    ]
