# Generated by Django 5.0.7 on 2024-07-16 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localproj', '0003_project_posted_by'),
        ('mentor', '0005_alter_mentors_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='posted_by',
            field=models.ForeignKey(default=36, on_delete=django.db.models.deletion.CASCADE, to='mentor.mentors'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localproj.projectcategory'),
        ),
    ]
