# Generated by Django 5.0.7 on 2024-07-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localproj', '0004_projectcategory_alter_project_posted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
