# Generated by Django 3.2.13 on 2024-07-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localproj', '0005_alter_project_project_name_delete_projectcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', models.TextField()),
            ],
        ),
    ]
