# Generated by Django 3.2.13 on 2024-07-10 13:42

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mentor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(max_length=100)),
                ('mentor_contact', models.CharField(default='Contact number not found 😔', max_length=15)),
                ('mentee_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('mentee_requirement', models.CharField(default='Mentee has mentioned nothing', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.category')),
            ],
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('contact', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default=None, max_length=100, null=True)),
                ('qualification', models.CharField(max_length=200, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('experience', models.IntegerField(verbose_name='Years of Experience')),
                ('start_weekday', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, null=True)),
                ('end_weekday', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, null=True)),
                ('time_from', models.TimeField(default='00:00', verbose_name='From')),
                ('time_to', models.TimeField(default='00:00', verbose_name='To')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Only JPEG/JPG files are allowed.'), mentor.models.validate_image_size])),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('Facebook', models.URLField(blank=True, null=True)),
                ('locality', models.CharField(choices=[('thiruvananthapuram', 'Thiruvananthapuram'), ('kollam', 'Kollam'), ('alappuzha', 'Alappuzha'), ('pathanamthitta', 'Pathanamthitta'), ('kottayam', 'Kottayam'), ('idukki', 'Idukki'), ('ernakulam', 'Ernakulam'), ('thrissur', 'Thrissur'), ('palakkad', 'Palakkad'), ('malappuram', 'Malappuram'), ('kozhikode', 'Kozhikode'), ('wayanad', 'Wayanad'), ('kannur', 'Kannur'), ('kasaragod', 'Kasaragod')], max_length=20)),
                ('about', models.TextField(max_length=500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('premium', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='mentors', to='mentor.Category')),
                ('specializations', models.ManyToManyField(blank=True, related_name='mentors', to='mentor.Specialization')),
            ],
        ),
    ]
