# Generated by Django 3.2.13 on 2024-07-11 00:18

import django.core.validators
from django.db import migrations, models
import mentor.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Only JPEG/JPG files are allowed.'), mentor.models.validate_image_size]),
            preserve_default=False,
        ),
    ]
