# Generated by Django 5.0.7 on 2024-07-12 09:53

import django.core.validators
import mentor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_alter_mentors_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='image',
            field=models.ImageField(blank=True, default='uploads/01_2.jpg', null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Only JPEG/JPG files are allowed.'), mentor.models.validate_image_size]),
        ),
    ]
