# Generated by Django 5.0.7 on 2024-07-12 10:01

import django.core.validators
import mentor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_alter_mentors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='image',
            field=models.ImageField(default='uploads/01_2.jpg', upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Only JPEG/JPG files are allowed.'), mentor.models.validate_image_size]),
        ),
    ]
