# Generated by Django 4.2.8 on 2024-01-01 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('experience', models.IntegerField()),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(5.0)])),
                ('time_availability', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=20)),
            ],
        ),
    ]
