# Generated by Django 4.2.3 on 2024-01-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0005_category_remove_mentors_category_mentors_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='expert_on',
            field=models.CharField(default='', max_length=20),
        ),
    ]
