# Generated by Django 4.2.3 on 2024-01-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0010_mentors_specializations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentors',
            options={'ordering': ['pub_date']},
        ),
    ]
