# Generated by Django 4.2.3 on 2024-01-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0011_alter_mentors_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentors',
            options={},
        ),
        migrations.RemoveField(
            model_name='mentors',
            name='specializations',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
