# Generated by Django 4.2.3 on 2024-01-03 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0012_alter_mentors_options_remove_mentors_specializations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorapp.category')),
            ],
        ),
        migrations.AddField(
            model_name='mentors',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='mentorapp.specialization'),
        ),
    ]
