# Generated by Django 4.2.3 on 2024-01-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0013_specialization_mentors_specializations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialization',
            old_name='name',
            new_name='specialist',
        ),
    ]
