# Generated by Django 4.2.3 on 2024-01-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0014_rename_name_specialization_specialist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentors',
            old_name='weekday',
            new_name='end_weekday',
        ),
        migrations.AddField(
            model_name='mentors',
            name='start_weekday',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, null=True),
        ),
    ]
