# Generated by Django 4.2.3 on 2024-01-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0015_rename_weekday_mentors_end_weekday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='Facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentors',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentors',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentors',
            name='locality',
            field=models.CharField(blank=True, choices=[('thiruvananthapuram', 'Thiruvananthapuram'), ('kollam', 'Kollam'), ('alappuzha', 'Alappuzha'), ('pathanamthitta', 'Pathanamthitta'), ('kottayam', 'Kottayam'), ('idukki', 'Idukki'), ('ernakulam', 'Ernakulam'), ('thrissur', 'Thrissur'), ('palakkad', 'Palakkad'), ('malappuram', 'Malappuram'), ('kozhikode', 'Kozhikode'), ('wayanad', 'Wayanad'), ('kannur', 'Kannur'), ('kasaragod', 'Kasaragod')], max_length=20, null=True),
        ),
    ]
