# Generated by Django 4.2.3 on 2024-01-05 07:01

import django.core.validators
from django.db import migrations, models
import mentorapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0019_alter_mentors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Only JPEG/JPG files are allowed.'), mentorapp.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='mentors',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='mentorapp.specialization'),
        ),
    ]
