# Generated by Django 4.2.3 on 2024-01-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0020_alter_mentors_image_alter_mentors_specializations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='mentorapp.specialization'),
        ),
    ]
