# Generated by Django 4.2.3 on 2024-01-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0021_alter_mentors_specializations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='locality',
            field=models.CharField(choices=[('thiruvananthapuram', 'Thiruvananthapuram'), ('kollam', 'Kollam'), ('alappuzha', 'Alappuzha'), ('pathanamthitta', 'Pathanamthitta'), ('kottayam', 'Kottayam'), ('idukki', 'Idukki'), ('ernakulam', 'Ernakulam'), ('thrissur', 'Thrissur'), ('palakkad', 'Palakkad'), ('malappuram', 'Malappuram'), ('kozhikode', 'Kozhikode'), ('wayanad', 'Wayanad'), ('kannur', 'Kannur'), ('kasaragod', 'Kasaragod')], max_length=20),
        ),
    ]
