# Generated by Django 4.2.3 on 2024-01-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0023_menteerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenteeRequest',
        ),
    ]
