# Generated by Django 4.2.3 on 2024-01-09 12:26

from django.db import migrations, models
import mentorapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0026_mentee_mentee_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='contact',
            field=models.CharField(default='', max_length=15, validators=[mentorapp.models.validate_phone_number]),
        ),
    ]
