# Generated by Django 4.2.3 on 2024-01-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0028_mentee_mentor_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='mentor_contact',
            field=models.CharField(default='Contact number not found 😔', max_length=15),
        ),
    ]
