# Generated by Django 4.2.3 on 2024-01-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0002_mentors_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentors',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='mentors',
            name='time_availability',
        ),
        migrations.AddField(
            model_name='mentors',
            name='time_from',
            field=models.TimeField(default='00:00', verbose_name='From'),
        ),
        migrations.AddField(
            model_name='mentors',
            name='time_to',
            field=models.TimeField(default='00:00', verbose_name='To'),
        ),
        migrations.AddField(
            model_name='mentors',
            name='weekday',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='mentors',
            name='experience',
            field=models.IntegerField(verbose_name='Years of Experience'),
        ),
    ]
