# Generated by Django 4.2.3 on 2024-01-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0003_remove_mentors_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='category',
            field=models.CharField(default='', max_length=20, verbose_name='Category'),
        ),
    ]
