# Generated by Django 4.2.3 on 2024-01-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0004_mentors_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mentors',
            name='category',
        ),
        migrations.AddField(
            model_name='mentors',
            name='categories',
            field=models.ManyToManyField(related_name='mentors', to='mentorapp.category'),
        ),
    ]
