# Generated by Django 4.2.3 on 2024-01-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0006_category_expert_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='expert_on',
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorapp.category')),
            ],
        ),
    ]
