# Generated by Django 4.2.3 on 2024-01-02 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0007_remove_category_expert_on_expertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorapp.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Expertise',
        ),
    ]
