# Generated by Django 4.2.3 on 2024-01-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0016_mentors_facebook_mentors_instagram_mentors_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='qualification',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
