# Generated by Django 4.2.3 on 2024-01-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0017_mentors_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='about',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
