# Generated by Django 4.2.3 on 2024-01-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0018_mentors_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
