# Generated by Django 4.2.3 on 2024-01-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0025_mentee'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='mentee_requirement',
            field=models.CharField(default='Mentee has mentioned nothing', max_length=500, null=True),
        ),
    ]
