# Generated by Django 4.2.3 on 2024-01-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0031_alter_mentee_mentor_contact_alter_mentors_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
